package tequila.dao.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CHANNEL_TYPE".
 */
public class ChannelType {

    private String name;
    private Long id;

    public ChannelType() {
    }

    public ChannelType(Long id) {
        this.id = id;
    }

    public ChannelType(String name, Long id) {
        this.name = name;
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
