package tequila.dao.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "POST".
 */
public class Post {

    private Long id;
    private String title;
    private String content;
    private String summary;
    private String type;
    private Integer traffic;
    private Integer questionId;
    private String titleImg;
    private java.util.Date createdAt;
    private java.util.Date lastUpdate;
    private Boolean published;
    private Boolean featured;
    private Boolean deleted;
    private Integer userId;
    private Integer expertId;
    private String tags;
    private Integer migrationId;
    private Integer answerCount;

    public Post() {
    }

    public Post(Long id) {
        this.id = id;
    }

    public Post(Long id, String title, String content, String summary, String type, Integer traffic, Integer questionId, String titleImg, java.util.Date createdAt, java.util.Date lastUpdate, Boolean published, Boolean featured, Boolean deleted, Integer userId, Integer expertId, String tags, Integer migrationId, Integer answerCount) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.summary = summary;
        this.type = type;
        this.traffic = traffic;
        this.questionId = questionId;
        this.titleImg = titleImg;
        this.createdAt = createdAt;
        this.lastUpdate = lastUpdate;
        this.published = published;
        this.featured = featured;
        this.deleted = deleted;
        this.userId = userId;
        this.expertId = expertId;
        this.tags = tags;
        this.migrationId = migrationId;
        this.answerCount = answerCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getTraffic() {
        return traffic;
    }

    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    public Integer getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    public String getTitleImg() {
        return titleImg;
    }

    public void setTitleImg(String titleImg) {
        this.titleImg = titleImg;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(java.util.Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Boolean getPublished() {
        return published;
    }

    public void setPublished(Boolean published) {
        this.published = published;
    }

    public Boolean getFeatured() {
        return featured;
    }

    public void setFeatured(Boolean featured) {
        this.featured = featured;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getExpertId() {
        return expertId;
    }

    public void setExpertId(Integer expertId) {
        this.expertId = expertId;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public Integer getMigrationId() {
        return migrationId;
    }

    public void setMigrationId(Integer migrationId) {
        this.migrationId = migrationId;
    }

    public Integer getAnswerCount() {
        return answerCount;
    }

    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }

}
