package tequila.dao.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private String username;
    private String nickname;
    private String email;
    private Boolean emailVerified;
    private String phone;
    private Boolean phoneVerified;
    private String wechatId;
    private String group;
    private String age;
    private String gender;
    private String portrait;
    private Integer status;
    private Double balance;
    private Boolean banned;
    private Boolean deleted;
    private java.util.Date createdAt;
    private java.util.Date lastLogin;
    private Integer migrationId;
    private Boolean isAdmin;
    private String groupName;
    private Integer expertId;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String username, String nickname, String email, Boolean emailVerified, String phone, Boolean phoneVerified, String wechatId, String group, String age, String gender, String portrait, Integer status, Double balance, Boolean banned, Boolean deleted, java.util.Date createdAt, java.util.Date lastLogin, Integer migrationId, Boolean isAdmin, String groupName, Integer expertId) {
        this.id = id;
        this.username = username;
        this.nickname = nickname;
        this.email = email;
        this.emailVerified = emailVerified;
        this.phone = phone;
        this.phoneVerified = phoneVerified;
        this.wechatId = wechatId;
        this.group = group;
        this.age = age;
        this.gender = gender;
        this.portrait = portrait;
        this.status = status;
        this.balance = balance;
        this.banned = banned;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.lastLogin = lastLogin;
        this.migrationId = migrationId;
        this.isAdmin = isAdmin;
        this.groupName = groupName;
        this.expertId = expertId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getEmailVerified() {
        return emailVerified;
    }

    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Boolean getPhoneVerified() {
        return phoneVerified;
    }

    public void setPhoneVerified(Boolean phoneVerified) {
        this.phoneVerified = phoneVerified;
    }

    public String getWechatId() {
        return wechatId;
    }

    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPortrait() {
        return portrait;
    }

    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public Boolean getBanned() {
        return banned;
    }

    public void setBanned(Boolean banned) {
        this.banned = banned;
    }

    public Boolean getDeleted() {
        return deleted;
    }

    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getLastLogin() {
        return lastLogin;
    }

    public void setLastLogin(java.util.Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    public Integer getMigrationId() {
        return migrationId;
    }

    public void setMigrationId(Integer migrationId) {
        this.migrationId = migrationId;
    }

    public Boolean getIsAdmin() {
        return isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Integer getExpertId() {
        return expertId;
    }

    public void setExpertId(Integer expertId) {
        this.expertId = expertId;
    }

}
